/* COMBO BOX
	STYLE PROPERTY   DESC
	Simple           combined open list
	Dropdown         Simple with dropdown button
	Drop List        Dropdown, closed by def

	LIST BOX MESSAGES    	COMBO BOX ANALOGS
	EM_GETSEL             CB_GETEDITSEL
	EM_SETSEL             CB_SETEDITSEL
	LB_ADDSTRING          CB_ADDSTRING
	LB_DELETESTRING       CB_DELETESTRING
	LB_GETCOUNT           CB_GETCOUNT
	LB_GETCURSEL          CB_GETCURSEL
	LB_GETTEXT            CB_GETLBTEXT
	LB_SETCURSEL          CB_SETCURSEL

	LIST BOX CODES                COMBO BOX ANALOGS
	EN_SETFOCUS, LBN_SETFOCUS     CBN_SETFOCUS
	EN_KILLFOCUS, LBN_KILLFOCUS   CBN_KILLFOCUS
	EN_UPDATE                     CBN_EDITUPDATE
	EN_CHANGE                     CBN_EDITCHANGE
	EN_ERRSPACE, LBN_ERRSPACE     CBN_ERRSPACE
	LBN_SELCHANGE                 CBN_SELCHANGE
	*/